import pickle
import subprocess
import re
import faiss
import numpy as np
import json
import time
import random


import streamlit as st

from sentence_transformers import SentenceTransformer
from pypdf import PdfReader

st.set_page_config(
    page_title="AeroMentor",
    page_icon="✈️"
)

st.title("✈️ AeroMentor")
st.write("Your Aviation AI Instructor")

quiz_questions = {
    "Aerodynamics": [

        {
            "question":
                "Which force opposes weight?",

            "options": [
                "Drag",
                "Lift",
                "Thrust",
                "Gravity"
            ],

            "answer":
                "Lift",

            "explanation":
                "Lift is the aerodynamic force that acts upward and opposes the aircraft's weight."
        },

        {
            "question":
                "Which force resists an aircraft's motion through the air?",

            "options": [
                "Lift",
                "Weight",
                "Drag",
                "Thrust"
            ],

            "answer":
                "Drag",

            "explanation":
                "Drag is the aerodynamic force that opposes motion through the air."
        },

        {
            "question":
                "Which force propels an aircraft forward?",

            "options": [
                "Lift",
                "Thrust",
                "Drag",
                "Weight"
            ],

            "answer":
                "Thrust",

            "explanation":
                "Thrust is generated by the aircraft's engines."
        },

        {
            "question":
                "Weight acts in which direction?",

            "options": [
                "Forward",
                "Backward",
                "Downward",
                "Upward"
            ],

            "answer":
                "Downward",

            "explanation":
                "Weight is the force of gravity acting downward on the aircraft."
        },

        {
            "question":
                "A stall is primarily caused by:",

            "options": [
                "High airspeed",
                "Excessive angle of attack",
                "Low engine power",
                "High altitude"
            ],

            "answer":
                "Excessive angle of attack",

            "explanation":
                "A stall occurs when the wing exceeds its critical angle of attack and can no longer produce sufficient lift."
        }

    ],

    "Commercial Aircraft": [

        {
            "question":
                "The Airbus A320 is primarily a:",

            "options": [
                "Cargo aircraft",
                "Narrow-body airliner",
                "Helicopter",
                "Military aircraft"
            ],

            "answer":
                "Narrow-body airliner",

            "explanation":
                "The Airbus A320 is a narrow-body commercial airliner designed for short- and medium-haul routes."
        },

        {
            "question":
                "Which company manufactures the Airbus A320?",

            "options": [
                "Boeing",
                "Airbus",
                "Embraer",
                "Bombardier"
            ],

            "answer":
                "Airbus",

            "explanation":
                "The Airbus A320 family is manufactured by Airbus."
        },

        {
            "question":
                "The Boeing 787 is commonly known as the:",

            "options": [
                "Dreamliner",
                "SkyKing",
                "Galaxy",
                "SuperJet"
            ],

            "answer":
                "Dreamliner",

            "explanation":
                "The Boeing 787 earned the name Dreamliner due to its advanced composite construction and efficiency."
        },

        {
            "question":
                "Which aircraft is the world's largest passenger airliner?",

            "options": [
                "A320",
                "B777",
                "A380",
                "B737"
            ],

            "answer":
                "A380",

            "explanation":
                "The Airbus A380 is the world's largest passenger aircraft."
        },

        {
            "question":
                "The Airbus A350 is mainly designed for:",

            "options": [
                "Regional flights",
                "Long-haul flights",
                "Cargo only",
                "Military transport"
            ],

            "answer":
                "Long-haul flights",

            "explanation":
                "The Airbus A350 is a modern long-range wide-body aircraft."
        }

    ],

    "Aircraft Systems": [

        {
            "question":
                "What does APU stand for?",

            "options": [
                "Auxiliary Power Unit",
                "Aircraft Power Utility",
                "Automatic Propulsion Unit",
                "Auxiliary Pressure Unit"
            ],

            "answer":
                "Auxiliary Power Unit",

            "explanation":
                "The APU provides electrical and pneumatic power when the engines are not operating."
        },

        {
            "question":
                "The primary purpose of landing gear is to:",

            "options": [
                "Generate lift",
                "Support the aircraft during takeoff and landing",
                "Reduce drag",
                "Power the aircraft"
            ],

            "answer":
                "Support the aircraft during takeoff and landing",

            "explanation":
                "Landing gear supports the aircraft while taxiing, taking off, and landing."
        },

        {
            "question":
                "Which aircraft system controls roll, pitch, and yaw?",

            "options": [
                "Fuel system",
                "Flight control system",
                "Hydraulic pump",
                "Electrical system"
            ],

            "answer":
                "Flight control system",

            "explanation":
                "Flight controls move the ailerons, elevators, and rudder to control aircraft attitude."
        },

        {
            "question":
                "Aircraft engines primarily produce:",

            "options": [
                "Lift",
                "Weight",
                "Thrust",
                "Drag"
            ],

            "answer":
                "Thrust",

            "explanation":
                "Aircraft engines generate thrust, which propels the aircraft forward."
        },

        {
            "question":
                "The fuel system is responsible for:",

            "options": [
                "Creating lift",
                "Supplying fuel to the engines",
                "Cooling passengers",
                "Operating the landing gear"
            ],

            "answer":
                "Supplying fuel to the engines",

            "explanation":
                "The fuel system safely stores and delivers fuel to the engines."
        }

    ],

    "Flight Operations": [

        {
            "question":
                "What phase of flight occurs immediately after takeoff?",

            "options": [
                "Landing",
                "Taxi",
                "Climb",
                "Shutdown"
            ],

            "answer":
                "Climb",

            "explanation":
                "After takeoff, the aircraft enters the climb phase."
        },

        {
            "question":
                "What is the purpose of taxiing?",

            "options": [
                "Cruise flight",
                "Moving the aircraft on the ground",
                "Landing",
                "Engine shutdown"
            ],

            "answer":
                "Moving the aircraft on the ground",

            "explanation":
                "Taxiing is the movement of an aircraft between the runway and parking areas."
        },

        {
            "question":
                "Which phase follows cruise?",

            "options": [
                "Taxi",
                "Descent",
                "Takeoff",
                "Pushback"
            ],

            "answer":
                "Descent",

            "explanation":
                "After cruising, an aircraft begins its descent toward the destination airport."
        },

        {
            "question":
                "Pilots perform a flare during:",

            "options": [
                "Takeoff",
                "Landing",
                "Cruise",
                "Taxi"
            ],

            "answer":
                "Landing",

            "explanation":
                "The flare reduces the rate of descent just before touchdown."
        },

        {
            "question":
                "Which phase occurs before takeoff?",

            "options": [
                "Taxi",
                "Cruise",
                "Landing",
                "Descent"
            ],

            "answer":
                "Taxi",

            "explanation":
                "Aircraft taxi from the gate to the runway before takeoff."
        }

    ],
}

with st.sidebar:

    st.header("⚙️ Settings")

    if st.button("🗑️ Clear Chat"):

        st.session_state.history = []

        st.rerun()

    st.divider()

    uploaded_file = st.file_uploader(
        "Upload a PDF",
        type=["pdf"]
    )

    if uploaded_file:

        st.success(
            f"Uploaded: {uploaded_file.name}"
        )
    st.divider()

    st.header(
        "✈️ Aviation Topic Explorer"
    )

    topics = {
        "Commercial Aircraft": [
            "A320",
            "A350",
            "A380",
            "B737",
            "B747",
            "B777",
            "B787"
        ],

        "Aerodynamics": [
            "Lift",
            "Drag",
            "Thrust",
            "Weight",
            "Angle of Attack",
            "Stalls"
        ],

        "Aircraft Systems": [
            "Engines",
            "APU",
            "Fuel System",
            "Landing Gear",
            "Flight Controls"
        ],

        "Flight Operations": [
            "V-speeds",
            "Takeoff",
            "Landing",
            "Climbs",
            "Descents"
        ]
    }

    topic_descriptions = {
        "A320":
            "Short-to-medium haul airliner",

        "A350":
            "Long-range wide-body airliner",

        "A380":
            "World's largest passenger airliner",

        "B737":
            "Popular narrow-body airliner",

        "B747":
            "Iconic jumbo jet",

        "B777":
            "Long-range twin-engine airliner",

        "B787":
            "Fuel-efficient Dreamliner",

        "Lift":
            "Force that opposes weight",

        "Drag":
            "Force resisting motion",

        "Thrust":
            "Forward force generated by engines",

        "Weight":
            "Gravitational force acting on the aircraft",

        "Angle of Attack":
            "Angle between the wing and airflow",

        "Stalls":
            "Loss of lift due to excessive angle of attack",

        "Engines":
            "Aircraft propulsion systems",

        "APU":
            "Auxiliary Power Unit",

        "Fuel System":
            "Stores and supplies fuel",

        "Landing Gear":
            "Supports aircraft during takeoff and landing",

        "Flight Controls":
            "Control surfaces for maneuvering",

        "V-speeds":
            "Critical operational speeds",

        "Takeoff":
            "Transition from ground to flight",

        "Landing":
            "Transition from flight to ground",

        "Climbs":
            "Gain of altitude",

        "Descents":
            "Loss of altitude"
    }

    selected_topic = st.selectbox(
        "Choose a topic",
        topics.keys()
    )

    st.subheader(
        "Related Topics"
    )

    for topic in topics[
        selected_topic
    ]:

        with st.container():
            

            st.markdown(
                f"📘 **{topic}**"
            )

            st.caption(
                topic_descriptions.get(
                    topic,
                    ""
                )
            )

            if st.button(
                f"🔍 Explore {topic}",
                key=f"topic_{topic}"
            ):

                st.session_state.topic_query = (
                    f"Explain {topic}"
                )
    
    st.divider()

    st.header(
        "🎓 Aviation Learning Mode"
    )

    quiz_topic = st.selectbox(
        "Quiz Topic",
        [
            "Aerodynamics",
            "Commercial Aircraft",
            "Aircraft Systems",
            "Flight Operations"
        ]
    )
    generate_quiz = st.button(
        "🎲 Generate Quiz"
    )

    if generate_quiz:

        st.session_state.quiz_list = (
            random.sample(
                quiz_questions[
                    quiz_topic
                ],
                len(
                    quiz_questions[
                        quiz_topic
                    ]
                )
            )
        )

        st.session_state.current_quiz_index = 0

        st.session_state.quiz = (
            st.session_state.quiz_list[0]
        )

        st.session_state.question_submitted = False

        st.session_state.quiz_score = 0
        st.session_state.questions_answered = 0
        st.session_state.quiz_number = 1

        

        st.session_state.question_submitted = False
        
    





@st.cache_resource
def load_model():
    return SentenceTransformer(
        "sentence-transformers/all-MiniLM-L6-v2"
    )

@st.cache_resource
def load_database():

    with open(
        "aviation_chunk_index.pkl",
        "rb"
    ) as file:

        return pickle.load(file)

model = load_model()
database = load_database()
with open(
    "data/aircraft_specs.json",
    "r"
) as file:

    aircraft_specs = json.load(file)

for chunk in database:
    if chunk["filename"] == "a350.txt":
        print(
            f"Chunk {chunk['chunk_number']}"
        )
        print(chunk["text"])
        print("----------------") 

@st.cache_resource
def load_faiss_index():

    return faiss.read_index(
        "aviation_faiss.index"
    )

index = load_faiss_index()
print(type(index))

uploaded_database = []

if uploaded_file:

    try:

        uploaded_file.seek(0)

        reader = PdfReader(
            uploaded_file
        )

    except Exception as e:

        st.error(
            f"Could not read PDF: {e}"
        )

        st.stop()

    uploaded_text = ""

    for page in reader.pages:

        page_text = page.extract_text()

        if page_text:
            uploaded_text += (
                page_text + "\n"
            )
    
    st.write(
        f"Pages: {len(reader.pages)}"
    )

    st.write(
        f"Characters: {len(uploaded_text)}"
    )

    uploaded_chunks = []

    chunk_size = 1000

    for i in range(
        0,
        len(uploaded_text),
        chunk_size
    ):

        chunk = uploaded_text[
            i:i + chunk_size
        ].strip()

        if chunk:
            uploaded_chunks.append(
                chunk
            )

    embeddings = model.encode(
        uploaded_chunks,
        show_progress_bar=True
    ).astype("float32")

    for chunk_number, (chunk, embedding) in enumerate(
        zip(uploaded_chunks, embeddings)
    ):
        uploaded_database.append(
            {
                "filename": uploaded_file.name,
                "chunk_number": chunk_number,
                "text": chunk,
                "embedding": embedding
            }
        )

    st.write(
        f"Chunks: {len(uploaded_chunks)}"
    )

    st.write(
        f"Embeddings: "
        f"{len(uploaded_database)}"
    )

if "history" not in st.session_state:

    st.session_state.history = []

if "quiz_score" not in st.session_state:
    st.session_state.quiz_score = 0

if "quiz_list" not in st.session_state:
    st.session_state.quiz_list = []

if "current_quiz_index" not in st.session_state:
    st.session_state.current_quiz_index = 0

if "questions_answered" not in st.session_state:
    st.session_state.questions_answered = 0

if "quiz_number" not in st.session_state:
    st.session_state.quiz_number = 1

if "question_submitted" not in st.session_state:
    st.session_state.question_submitted = False

if "quiz" in st.session_state:
    st.header(
        "🎓 Aviation Quiz"
    )

    st.write(
        f"Question "
        f"{st.session_state.quiz_number}"
    )



    st.progress(
        min(
            st.session_state.questions_answered / 5,
            1.0
        )
    )

    quiz = (
        st.session_state.quiz
    )

    st.write(
        f"**Question:** "
        f"{quiz['question']}"
    )

    user_answer = st.radio(
        "Choose an answer",
        quiz["options"]
    )

    submit_answer = st.button(
        "✅ Submit Answer"
    )

    if (
        submit_answer
        and
        not st.session_state.question_submitted
    ):

        if (
            user_answer
            ==
            quiz["answer"]
        ):

            st.success(
                "Correct! 🎉"
            )

            st.session_state.quiz_score += 1

        else:

            st.error(
                f"Incorrect. "
                f"The correct answer is "
                f"{quiz['answer']}."
            )

        st.session_state.questions_answered += 1

        st.session_state.quiz_number += 1
        st.session_state.question_submitted = True

        st.info(
            f"Explanation:\n\n"
            f"{quiz['explanation']}"
        )
        st.metric(
            "Score",
            f"{st.session_state.quiz_score}/"
            f"{st.session_state.questions_answered}"
        )
        if (
            st.session_state.questions_answered
            >= 5
        ):

            st.balloons()

            st.success(
                f"Quiz Complete! "
                f"Final Score: "
                f"{st.session_state.quiz_score}/5"
            )
            
if (
    st.session_state.questions_answered
    >= 5
):

    st.balloons()

    st.success(
        f"Quiz Complete! "
        f"Final Score: "
        f"{st.session_state.quiz_score}/5"
    )

    if st.button(
        "🔄 Restart Quiz"
    ):

        st.session_state.quiz_score = 0
        st.session_state.questions_answered = 0
        st.session_state.quiz_number = 1
        st.session_state.question_submitted = False

        del st.session_state["quiz"]

        st.rerun()

            
if (
    st.session_state.questions_answered < 5
    and
    st.session_state.question_submitted
):

    if st.button(
        "🎲 Next Question"
    ):

        st.session_state.current_quiz_index += 1

        if (
            st.session_state.current_quiz_index
            <
            len(
                st.session_state.quiz_list
            )
        ):

            st.session_state.quiz = (
                st.session_state.quiz_list[
                    st.session_state.current_quiz_index
                ]
            )

        st.session_state.question_submitted = False

        st.rerun()

        st.session_state.quiz = random.choice(
            quiz_questions[
                quiz_topic
            ]
        )

        st.session_state.question_submitted = False

        st.rerun()

question = st.chat_input(
    "Ask an aviation question:"
)
if (
    "topic_query"
    in st.session_state
):

    question = (
        st.session_state
        .topic_query
    )

    del st.session_state[
        "topic_query"
    ]

for user_question, assistant_answer in st.session_state.history:

    with st.chat_message("user"):
        st.write(user_question)

    with st.chat_message("assistant"):
        st.write(assistant_answer)


if question:

    with st.chat_message("user"):
        st.write(question)
    
    start_time = time.time()

    history_text = ""

    for (
        user_question,
        assistant_answer
    ) in st.session_state.history[-3:]:

        history_text += (
            f"\nUser: {user_question}\n"
            f"Assistant: {assistant_answer}\n"
        )

    follow_up_words = [
        "it",
        "its",
        "they",
        "them",
        "that",
        "those",
        "these"
    ]

    question_lower = question.lower()

    selected_aircraft = None

    for plane in aircraft_specs:

        if plane in question_lower:
            selected_aircraft = plane
            break

    aircraft = [
        "a320",
        "a350",
        "a380",
        "b737",
        "b747",
        "b777",
        "b787"
    ]


    is_follow_up = any(
        word in question_lower.split()
        for word in follow_up_words
    )


    last_aircraft = ""

    for plane in aircraft:
        if plane in history_text.lower():
            last_aircraft = plane.upper()

    if selected_aircraft:
        search_query = (
            f"{selected_aircraft} "
            f"{question}"
        )

    elif is_follow_up and last_aircraft:
        search_query = (
            f"{last_aircraft} "
            f"{question}"
        )

    else:
        search_query = question



    question_embedding = model.encode(
        [search_query]
    ).astype("float32")

    uploaded_scores = []

    for chunk in uploaded_database:

        embedding = np.array(
            chunk["embedding"],
            dtype="float32"
        )

        similarity = np.dot(
            question_embedding[0],
            embedding
        )

        uploaded_scores.append(
            (
                chunk["filename"],
                chunk["chunk_number"],
                similarity,
                chunk["text"]
            )
        )

    uploaded_scores.sort(
        key=lambda x: x[2],
        reverse=True
    )

    print("\nUPLOADED PDF SCORES:")

    for (
        filename,
        chunk_number,
        score,
        text
    ) in uploaded_scores:

        print(
            f"{filename}"
            f" | Chunk {chunk_number}"
            f" | Score {score}"
        )


   



    distances, indices = index.search(
        question_embedding,
        100
    )

    print("\nFAISS RESULTS:")

    for i in indices[0]:
        chunk = database[i]
        print(
            f"{chunk['filename']}"
            f" | Chunk {chunk['chunk_number']}"
        )

    scores = []

    for i in indices[0]:

        chunk = database[i]

        position = list(
            indices[0]
        ).index(i)

        similarity = -float(
            distances[0][position]
        )

        if "engine" in question_lower:
            if "engine" in chunk["text"].lower():
                similarity += 0.50

        filename_lower = chunk["filename"].lower()

        for plane in aircraft:
            if (
                plane in search_query.lower()
                and plane in filename_lower
            ):
                similarity += 0.20

        scores.append(
            (
                chunk["filename"],
                chunk["chunk_number"],
                similarity,
                chunk["text"]
            )
        )

    scores.sort(
        key=lambda x: x[2],
        reverse=True
    )

    top_chunks = scores[:8]

    all_scores = (
        scores +
        uploaded_scores
    )

    all_scores.sort(
        key=lambda x: x[2],
        reverse=True
    )

    top_chunks = all_scores[:8]

    source_files = set()

    for (
        filename,
        chunk_number,
        score,
        text
    ) in top_chunks:

        source_files.add(filename)

    source_counts = {}

    for (
        filename,
        chunk_number,
        score,
        text
    ) in top_chunks:

        if filename not in source_counts:
            source_counts[filename] = 0

        source_counts[filename] += 1

    top_source = max(
        source_counts,
        key=source_counts.get
    )

    source_names = {
        "phak.txt":
            "FAA Pilot's Handbook of Aeronautical Knowledge",

        "airplane_flying_handbook.txt":
            "FAA Airplane Flying Handbook"
    }

    top_source_name = source_names.get(
        top_source,
        top_source
    )

    retrieval_mode = (
        "Knowledge Base + Uploaded PDF"
        if uploaded_database
        else
        "Knowledge Base"
    )

    print("\nTOP CHUNKS:")

    for filename, chunk_number, score, text in top_chunks:
        print(
            f"{filename}"
            f" | Chunk {chunk_number}"
        )
        print(text[:200])
        print("----------------")



    context = ""

    for filename, chunk_number, score, text in top_chunks:

        context += (
            f"\n\nSource: {filename}"
            f" | Chunk: {chunk_number}\n"
        )

        context += text


    prompt = f"""
You are AeroMentor, an aviation instructor.

Answer ONLY using the provided context.

If the answer is present in the context,
answer using only that information.

If the answer truly cannot be found,
say:
"I do not have enough information in my knowledge base."

Previous Conversation:
{history_text}

Context:
{context}

Question:
{question}

Answer:
"""



    with st.spinner(
        "AeroMentor is thinking..."
    ):

        result = subprocess.run(
            ["ollama", "run", "llama3", prompt],
            capture_output=True,
            text=True
        )



    clean_output = re.sub(
        r"\x1b\[[0-9;]*[A-Za-z]",
        "",
        result.stdout
    )

    response_time = (
        time.time()
        - start_time
    )

    with st.chat_message("assistant"):
        st.write(clean_output)

    with st.expander(
        "📊 Retrieval Metrics"
    ):

        col1, col2 = st.columns(2)

        with col1:

            st.metric(
                "Knowledge Base",
                f"{len(database)} chunks"
            )

            st.metric(
                "Retrieved Chunks",
                len(top_chunks)
            )
        st.divider()

    
        with col2:

            st.metric(
                "Sources Used",
                len(source_files)
            )

            st.metric(
                "Response Time",
                f"{response_time:.2f}s"
            )
        
        st.divider()

        st.write(
            f"**Query:** {question}"
        )

        st.write(
            f"**Retrieval Mode:** "
            f"{retrieval_mode}"
        )

        st.write(
            "**Embedding Model:** "
            "all-MiniLM-L6-v2"
        )

        st.write(
            f"**Top Source:** "
            f"{top_source_name}"
        )

        for (
            filename,
            chunk_number,
            score,
            text
        ) in top_chunks:

            st.write(
                f"{filename} | "
                f"Chunk {chunk_number}"
            )


    if selected_aircraft:

        specs = aircraft_specs[
            selected_aircraft
        ]

        st.subheader(
            f"✈️ {specs['name']}"
        )

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "Passengers",
                specs["passengers"]
            )

            st.metric(
                "Range",
                specs["range"]
            )

        with col2:
            st.metric(
                "Cruise Speed",
                specs["cruise_speed"]
            )

            st.metric(
                "Engines",
                specs["engines"]
            )

        st.caption(
            specs["role"]
        )

    st.session_state.history.append(
        (
            question,
            clean_output
        )
    )

    source_names = {
        "phak.txt":
            "FAA Pilot's Handbook of Aeronautical Knowledge",

        "airplane_flying_handbook.txt":
            "FAA Airplane Flying Handbook"
    }

    sources = {}

    with st.expander("📚 Sources"):

        for (
            filename,
            chunk_number,
            score,
            text
        ) in top_chunks:

            if filename not in sources:
                sources[filename] = []

            sources[filename].append(
                chunk_number
            )

        for (
            filename,
            chunks
        ) in sources.items():

            display_name = source_names.get(
                filename,
                filename
            )

            st.write(
                f"📄 {display_name}"
            )

            st.caption(
                f"Retrieved Chunks: {len(chunks)}"
            )

            st.caption(
                "Chunk IDs: " +
                ", ".join(
                    str(chunk)
                    for chunk in chunks
                )
            )

